
/**
 * Add Education
 *
 *
 */

export const ADD_EDUCATION_SUCCESS = 'ADD_EDUCATION__SUCCESS'
export const ADD_EDUCATION_FAILED = 'ADD_EDUCATION_FAILED'
export const ADD_EDUCATION_REQUEST = 'ADD_EDUCATION_REQUEST'

export const CREATE_EDUCATION = 'CREATE_EDUCATION'
export const EDIT_EDUCATION = 'EDIT_EDUCATION'
