
export const GET_MY_PROFILE_SUCCESS = 'GET_MY_PROFILE_SUCCESS'
export const GET_MY_PROFILE_FAILED = 'GET_MY_PROFILE_FAILED'
export const GET_MY_PROFILE_REQUEST = 'GET_MY_PROFILE_REQUEST'

export const INVALIDATE_USER = 'INVALIDATE_USER'
