
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS'
export const UPLOAD_FILE_FAILED = 'UPLOAD_FILE_FAILED'
export const UPLOAD_FILE_REQUEST = 'UPLOAD_FILE_REQUEST'

export const CONVERT_PDF_SUCCESS = 'CONVERT_PDF_SUCCESS'
export const CONVERT_PDF_FAILED = 'CONVERT_PDF_FAILED'
export const CONVERT_PDF_REQUEST = 'CONVERT_PDF_REQUEST'

export const INVALIDATE_CONVERTER = 'INVALIDATE_CONVERTER'

export const ADD_DROPPED_FILE = 'ADD_DROPPED_FILE'
