
export const ASK_WIKIPEDIA_SUCCESS = 'ASK_WIKIPEDIA_SUCCESS'
export const ASK_WIKIPEDIA_FAILED = 'ASK_WIKIPEDIA_FAILED'
export const ASK_WIKIPEDIA_REQUEST = 'ASK_WIKIPEDIA_REQUEST'
export const VALIDATE_DATA_SUCCESS = 'VALIDATE_DATA_SUCCESS'

export const UPDATE_MAX_RESULTS = 'UPDATE_MAX_RESULTS'

export const ASK_WIKIPEDIA_AWAIT = 'ASK_WIKIPEDIA_AWAIT'
