export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'
export const CONTINUE_WITH_LINKEDIN_SUCCESS = 'CONTINUE_WITH_LINKEDIN_SUCCESS'
export const CONTINUE_WITH_GOOGLE_SUCCESS = 'CONTINUE_WITH_GOOGLE_SUCCESS'
