
/**
 *
 * Writing
 *
 */

export const RENDER_MICROPHONE = 'RENDER_MICROPHONE'

export const START = 'START'
export const STOP = 'STOP'
export const HAS_STOPPED = 'HAS_STOPPED'

export const VALIDATE_DATA_SUCCESS = 'VALIDATE_DATA_SUCCESS'
export const VALIDATE_DATA_FAILED = 'VALIDATED_DATA_FAILED'
export const VALIDATE_DATA_REQUEST = 'VALIDATED_DATA_REQUEST'
